spring:
  datasource:
    password: af927b58bc0607ff2caff00707028ec79f0e3e1a80ca0a56fc84dd413bce5d03
    username: umbimunmfyrpvg
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://umbimunmfyrpvg:af927b58bc0607ff2caff00707028ec79f0e3e1a80ca0a56fc84dd413bce5d03@ec2-54-157-16-196.compute-1.amazonaws.com:5432/d798q16sp9s600
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  sql:
    init:
      mode: never
#      mode: always
  main:
    allow-circular-references: true
    lazy-initialization: true
    allow-bean-definition-overriding: true
  thymeleaf:
    enabled: true
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



cloudinary:
  name: itransitionuz
  apiKey: 786711345455842
  apiSecret: OMq2W5RSMZzJgYzMtk01c8h57ho
