spring:
  datasource:
    password: 3255b59dc30449a07dbddd79189c5b03a82413eaa5465c544c933898d42c0d6f
    username: fwaakntgfjczvy
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-223-169-166.compute-1.amazonaws.com:5432/d2vn6849n2i5g9

  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: update
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        search:
          backend:
            type: lucene
            directory.root: ./data/index

  sql:
    init:
#      mode: never
      mode: always
  main:
    allow-circular-references: true
    lazy-initialization: true
    allow-bean-definition-overriding: true
  thymeleaf:
    enabled: true
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



cloudinary:
  name: itransitionuz
  apiKey: 786711345455842
  apiSecret: OMq2W5RSMZzJgYzMtk01c8h57ho

