server:
  port: 8080

spring:
  datasource:
    password: root123
    username: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/course_work
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create
  sql:
    init:
      mode: never
#      mode: always
  main:
    allow-circular-references: true
    lazy-initialization: true
    allow-bean-definition-overriding: true
  thymeleaf:
    enabled: true
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



cloudinary:
  name: itransitionuz
  apiKey: 786711345455842
  apiSecret: OMq2W5RSMZzJgYzMtk01c8h57ho
